# Generated by Django 6.0.5 on 2026-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificate_lesson_lessonprogress_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='course_demo_videos/'),
        ),
    ]
